// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv6w8YWz0C7gnsezynUCNXa9qpyWTXQtQ',
    appId: '1:66810025667:web:aeb18af0baa69c6da2f476',
    messagingSenderId: '66810025667',
    projectId: 'rimlines',
    authDomain: 'rimlines.firebaseapp.com',
    storageBucket: 'rimlines.appspot.com',
    measurementId: 'G-X7GP6G3DK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjoonHORJoU0psbEMvIuaQgo-hJTGNJhI',
    appId: '1:66810025667:android:93c6cac510498cb7a2f476',
    messagingSenderId: '66810025667',
    projectId: 'rimlines',
    storageBucket: 'rimlines.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_FBso1y8lp6vpWmrjIbhzsL_LMzuzfkc',
    appId: '1:66810025667:ios:90322380ec517ca3a2f476',
    messagingSenderId: '66810025667',
    projectId: 'rimlines',
    storageBucket: 'rimlines.appspot.com',
    iosClientId: '66810025667-l9o0pdh38pf9gc3bg704nqc21svmfob9.apps.googleusercontent.com',
    iosBundleId: 'com.rimlines.client',
  );
}
